// SPDX-FileCopyrightText: (C) 2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: infrainv/infrainv.proto

package infrainv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchemaExtension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indexes       []*Index               `protobuf:"bytes,1,rep,name=indexes" json:"indexes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaExtension) Reset() {
	*x = SchemaExtension{}
	mi := &file_infrainv_infrainv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaExtension) ProtoMessage() {}

func (x *SchemaExtension) ProtoReflect() protoreflect.Message {
	mi := &file_infrainv_infrainv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaExtension.ProtoReflect.Descriptor instead.
func (*SchemaExtension) Descriptor() ([]byte, []int) {
	return file_infrainv_infrainv_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaExtension) GetIndexes() []*Index {
	if x != nil {
		return x.Indexes
	}
	return nil
}

type Index struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`      // Name of index, autogenerated if not provided.
	Fields                []string               `protobuf:"bytes,2,rep,name=fields" json:"fields,omitempty"`  // Name of fields being part of defined index.
	Unique                *bool                  `protobuf:"varint,3,req,name=unique" json:"unique,omitempty"` // Uniqueness flag causes created index unique.
	PartialIndexCondition *string                `protobuf:"bytes,4,opt,name=partialIndexCondition" json:"partialIndexCondition,omitempty"`
	// When non-empty, builds ent index.Edges(...) instead of index.Fields(...).
	Edges         []string `protobuf:"bytes,5,rep,name=edges" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_infrainv_infrainv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_infrainv_infrainv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_infrainv_infrainv_proto_rawDescGZIP(), []int{1}
}

func (x *Index) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Index) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Index) GetUnique() bool {
	if x != nil && x.Unique != nil {
		return *x.Unique
	}
	return false
}

func (x *Index) GetPartialIndexCondition() string {
	if x != nil && x.PartialIndexCondition != nil {
		return *x.PartialIndexCondition
	}
	return ""
}

func (x *Index) GetEdges() []string {
	if x != nil {
		return x.Edges
	}
	return nil
}

var file_infrainv_infrainv_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*SchemaExtension)(nil),
		Field:         8086,
		Name:          "infrainv.schemaExtension",
		Tag:           "bytes,8086,opt,name=schemaExtension",
		Filename:      "infrainv/infrainv.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional infrainv.SchemaExtension schemaExtension = 8086;
	E_SchemaExtension = &file_infrainv_infrainv_proto_extTypes[0]
)

var File_infrainv_infrainv_proto protoreflect.FileDescriptor

const file_infrainv_infrainv_proto_rawDesc = "" +
	"\n" +
	"\x17infrainv/infrainv.proto\x12\binfrainv\x1a google/protobuf/descriptor.proto\"<\n" +
	"\x0fSchemaExtension\x12)\n" +
	"\aindexes\x18\x01 \x03(\v2\x0f.infrainv.IndexR\aindexes\"\x97\x01\n" +
	"\x05Index\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\x12\x16\n" +
	"\x06unique\x18\x03 \x02(\bR\x06unique\x124\n" +
	"\x15partialIndexCondition\x18\x04 \x01(\tR\x15partialIndexCondition\x12\x14\n" +
	"\x05edges\x18\x05 \x03(\tR\x05edges:e\n" +
	"\x0fschemaExtension\x12\x1f.google.protobuf.MessageOptions\x18\x96? \x01(\v2\x19.infrainv.SchemaExtensionR\x0fschemaExtensionBMZKgithub.com/open-edge-platform/infra-core/inventory/v2/pkg/infrainv;infrainv"

var (
	file_infrainv_infrainv_proto_rawDescOnce sync.Once
	file_infrainv_infrainv_proto_rawDescData []byte
)

func file_infrainv_infrainv_proto_rawDescGZIP() []byte {
	file_infrainv_infrainv_proto_rawDescOnce.Do(func() {
		file_infrainv_infrainv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infrainv_infrainv_proto_rawDesc), len(file_infrainv_infrainv_proto_rawDesc)))
	})
	return file_infrainv_infrainv_proto_rawDescData
}

var file_infrainv_infrainv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_infrainv_infrainv_proto_goTypes = []any{
	(*SchemaExtension)(nil),             // 0: infrainv.SchemaExtension
	(*Index)(nil),                       // 1: infrainv.Index
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
}
var file_infrainv_infrainv_proto_depIdxs = []int32{
	1, // 0: infrainv.SchemaExtension.indexes:type_name -> infrainv.Index
	2, // 1: infrainv.schemaExtension:extendee -> google.protobuf.MessageOptions
	0, // 2: infrainv.schemaExtension:type_name -> infrainv.SchemaExtension
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_infrainv_infrainv_proto_init() }
func file_infrainv_infrainv_proto_init() {
	if File_infrainv_infrainv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infrainv_infrainv_proto_rawDesc), len(file_infrainv_infrainv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_infrainv_infrainv_proto_goTypes,
		DependencyIndexes: file_infrainv_infrainv_proto_depIdxs,
		MessageInfos:      file_infrainv_infrainv_proto_msgTypes,
		ExtensionInfos:    file_infrainv_infrainv_proto_extTypes,
	}.Build()
	File_infrainv_infrainv_proto = out.File
	file_infrainv_infrainv_proto_goTypes = nil
	file_infrainv_infrainv_proto_depIdxs = nil
}
