// SPDX-FileCopyrightText: (C) 2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: remoteaccess/v1/remoteaccess.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "entgo.io/contrib/entproto/cmd/protoc-gen-ent/options/ent"
	v1 "github.com/open-edge-platform/infra-core/inventory/v2/pkg/api/compute/v1"
	v11 "github.com/open-edge-platform/infra-core/inventory/v2/pkg/api/status/v1"
	_ "github.com/open-edge-platform/infra-core/inventory/v2/pkg/infrainv"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents the Remote Access state, used for both current and desired state.
type RemoteAccessState int32

const (
	RemoteAccessState_REMOTE_ACCESS_STATE_UNSPECIFIED RemoteAccessState = 0
	RemoteAccessState_REMOTE_ACCESS_STATE_DELETED     RemoteAccessState = 1
	RemoteAccessState_REMOTE_ACCESS_STATE_ERROR       RemoteAccessState = 2
	RemoteAccessState_REMOTE_ACCESS_STATE_ENABLED     RemoteAccessState = 3
	RemoteAccessState_REMOTE_ACCESS_STATE_DISABLED    RemoteAccessState = 4
	RemoteAccessState_REMOTE_ACCESS_STATE_CONFIGURED  RemoteAccessState = 5
)

// Enum value maps for RemoteAccessState.
var (
	RemoteAccessState_name = map[int32]string{
		0: "REMOTE_ACCESS_STATE_UNSPECIFIED",
		1: "REMOTE_ACCESS_STATE_DELETED",
		2: "REMOTE_ACCESS_STATE_ERROR",
		3: "REMOTE_ACCESS_STATE_ENABLED",
		4: "REMOTE_ACCESS_STATE_DISABLED",
		5: "REMOTE_ACCESS_STATE_CONFIGURED",
	}
	RemoteAccessState_value = map[string]int32{
		"REMOTE_ACCESS_STATE_UNSPECIFIED": 0,
		"REMOTE_ACCESS_STATE_DELETED":     1,
		"REMOTE_ACCESS_STATE_ERROR":       2,
		"REMOTE_ACCESS_STATE_ENABLED":     3,
		"REMOTE_ACCESS_STATE_DISABLED":    4,
		"REMOTE_ACCESS_STATE_CONFIGURED":  5,
	}
)

func (x RemoteAccessState) Enum() *RemoteAccessState {
	p := new(RemoteAccessState)
	*p = x
	return p
}

func (x RemoteAccessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteAccessState) Descriptor() protoreflect.EnumDescriptor {
	return file_remoteaccess_v1_remoteaccess_proto_enumTypes[0].Descriptor()
}

func (RemoteAccessState) Type() protoreflect.EnumType {
	return &file_remoteaccess_v1_remoteaccess_proto_enumTypes[0]
}

func (x RemoteAccessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteAccessState.Descriptor instead.
func (RemoteAccessState) EnumDescriptor() ([]byte, []int) {
	return file_remoteaccess_v1_remoteaccess_proto_rawDescGZIP(), []int{0}
}

type RemoteAccessConfiguration struct {
	state protoimpl.MessageState
	// resource identifier
	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// Resource ID of related Instance resource
	Instance *v1.InstanceResource `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	// Remote access expiration timestamp
	ExpirationTimestamp uint64 `protobuf:"varint,4,opt,name=expiration_timestamp,json=expirationTimestamp,proto3" json:"expiration_timestamp,omitempty"`
	// Port terminating reverse SSH tunnel (on orchestrator side), RAP
	// Set by resource manager.
	LocalPort uint32 `protobuf:"varint,5,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	// RAP WebSocket host used by the agent to establish connection.
	ProxyHost string `protobuf:"bytes,6,opt,name=proxy_host,json=proxyHost,proto3" json:"proxy_host,omitempty"`
	// Name of remote user configured on SSH server running on EN
	// Set by resource manager.
	User string `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	// Shared secret or session token for agent authentication to RAP.
	SessionToken string `protobuf:"bytes,8,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	// Host on the edge side where the agent should forward traffic (e.g. 127.0.0.1). ex. Xterm frontend
	TargetHost string `protobuf:"bytes,9,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	// Port on the edge side where the agent should forward traffic (e.g. 22). ex. Xterm frontend
	TargetPort uint32 `protobuf:"varint,10,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	// Expresses current state of remote  access.
	// Managed by resource manager on behalf of provider.
	CurrentState RemoteAccessState `protobuf:"varint,11,opt,name=current_state,json=currentState,proto3,enum=remoteaccess.v1.RemoteAccessState" json:"current_state,omitempty"`
	// Expresses desired state of remote access. Set by an administrator.
	DesiredState RemoteAccessState `protobuf:"varint,12,opt,name=desired_state,json=desiredState,proto3,enum=remoteaccess.v1.RemoteAccessState" json:"desired_state,omitempty"`
	// A group of fields describing the remote access configuration.
	// Configuration status of the resource according to the provider.
	// configuration_status, configuration_status_indicator and configuration_status_timestamp
	// should always be updated in one shot.
	ConfigurationStatus string `protobuf:"bytes,13,opt,name=configuration_status,json=configurationStatus,proto3" json:"configuration_status,omitempty"` // textual message that describes the update status of Instance. Set by RMs only.
	// Indicates interpretation of configuration_status. Set by RMs only.
	ConfigurationStatusIndicator v11.StatusIndication `protobuf:"varint,14,opt,name=configuration_status_indicator,json=configurationStatusIndicator,proto3,enum=status.v1.StatusIndication" json:"configuration_status_indicator,omitempty"`
	// UTC timestamp when status was last changed. Set by RMs only.
	ConfigurationStatusTimestamp uint64 `protobuf:"varint,15,opt,name=configuration_status_timestamp,json=configurationStatusTimestamp,proto3" json:"configuration_status_timestamp,omitempty"`
	TenantId                     string `protobuf:"bytes,100,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`    // Tenant Identifier
	CreatedAt                    string `protobuf:"bytes,200,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Creation timestamp
	UpdatedAt                    string `protobuf:"bytes,201,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Update timestamp
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RemoteAccessConfiguration) Reset() {
	*x = RemoteAccessConfiguration{}
	mi := &file_remoteaccess_v1_remoteaccess_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteAccessConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteAccessConfiguration) ProtoMessage() {}

func (x *RemoteAccessConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_remoteaccess_v1_remoteaccess_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteAccessConfiguration.ProtoReflect.Descriptor instead.
func (*RemoteAccessConfiguration) Descriptor() ([]byte, []int) {
	return file_remoteaccess_v1_remoteaccess_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteAccessConfiguration) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *RemoteAccessConfiguration) GetInstance() *v1.InstanceResource {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *RemoteAccessConfiguration) GetExpirationTimestamp() uint64 {
	if x != nil {
		return x.ExpirationTimestamp
	}
	return 0
}

func (x *RemoteAccessConfiguration) GetLocalPort() uint32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *RemoteAccessConfiguration) GetProxyHost() string {
	if x != nil {
		return x.ProxyHost
	}
	return ""
}

func (x *RemoteAccessConfiguration) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RemoteAccessConfiguration) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *RemoteAccessConfiguration) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *RemoteAccessConfiguration) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *RemoteAccessConfiguration) GetCurrentState() RemoteAccessState {
	if x != nil {
		return x.CurrentState
	}
	return RemoteAccessState_REMOTE_ACCESS_STATE_UNSPECIFIED
}

func (x *RemoteAccessConfiguration) GetDesiredState() RemoteAccessState {
	if x != nil {
		return x.DesiredState
	}
	return RemoteAccessState_REMOTE_ACCESS_STATE_UNSPECIFIED
}

func (x *RemoteAccessConfiguration) GetConfigurationStatus() string {
	if x != nil {
		return x.ConfigurationStatus
	}
	return ""
}

func (x *RemoteAccessConfiguration) GetConfigurationStatusIndicator() v11.StatusIndication {
	if x != nil {
		return x.ConfigurationStatusIndicator
	}
	return v11.StatusIndication(0)
}

func (x *RemoteAccessConfiguration) GetConfigurationStatusTimestamp() uint64 {
	if x != nil {
		return x.ConfigurationStatusTimestamp
	}
	return 0
}

func (x *RemoteAccessConfiguration) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RemoteAccessConfiguration) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RemoteAccessConfiguration) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_remoteaccess_v1_remoteaccess_proto protoreflect.FileDescriptor

const file_remoteaccess_v1_remoteaccess_proto_rawDesc = "" +
	"\n" +
	"\"remoteaccess/v1/remoteaccess.proto\x12\x0fremoteaccess.v1\x1a\x1bbuf/validate/validate.proto\x1a\x18compute/v1/compute.proto\x1a\x0eent/opts.proto\x1a\x17infrainv/infrainv.proto\x1a\x16status/v1/status.proto\"\x8b\t\n" +
	"\x19RemoteAccessConfiguration\x12J\n" +
	"\vresource_id\x18\x01 \x01(\tB)\xbaH \xd8\x01\x01r\x1b(\x132\x17^rmtacconf-[0-9a-f]{8}$\xba\xa6I\x02\x18\x01R\n" +
	"resourceId\x12B\n" +
	"\binstance\x18\x02 \x01(\v2\x1c.compute.v1.InstanceResourceB\b¦I\x04\b\x01\x18\x01R\binstance\x12A\n" +
	"\x14expiration_timestamp\x18\x04 \x01(\x04B\x0e\xbaH\x03\xd8\x01\x01\xba\xa6I\x04\b\x00(\x01R\x13expirationTimestamp\x126\n" +
	"\n" +
	"local_port\x18\x05 \x01(\rB\x17\xbaH\f\xd8\x01\x01*\a\x18\xff\xff\x03(\x80\b\xba\xa6I\x04\b\x01\x18\x01R\tlocalPort\x12/\n" +
	"\n" +
	"proxy_host\x18\x06 \x01(\tB\x10\xbaH\a\xd8\x01\x01r\x02\x10\x03\xba\xa6I\x02\b\x01R\tproxyHost\x12$\n" +
	"\x04user\x18\a \x01(\tB\x10\xbaH\a\xd8\x01\x01r\x02\x18\x14\xba\xa6I\x02\b\x01R\x04user\x125\n" +
	"\rsession_token\x18\b \x01(\tB\x10\xbaH\a\xd8\x01\x01r\x02\x10\x03\xba\xa6I\x02\b\x01R\fsessionToken\x124\n" +
	"\vtarget_host\x18\t \x01(\tB\x13\xbaH\n" +
	"\xd8\x01\x01r\x05\x10\x01\x18\xff\x01\xba\xa6I\x02\b\x01R\n" +
	"targetHost\x125\n" +
	"\vtarget_port\x18\n" +
	" \x01(\rB\x14\xbaH\v\xd8\x01\x01*\x06\x18\xff\xff\x03(\x01\xba\xa6I\x02\b\x01R\n" +
	"targetPort\x12O\n" +
	"\rcurrent_state\x18\v \x01(\x0e2\".remoteaccess.v1.RemoteAccessStateB\x06\xba\xa6I\x02\b\x01R\fcurrentState\x12G\n" +
	"\rdesired_state\x18\f \x01(\x0e2\".remoteaccess.v1.RemoteAccessStateR\fdesiredState\x12D\n" +
	"\x14configuration_status\x18\r \x01(\tB\x11\xbaH\b\xd8\x01\x01r\x03(\x80\b\xba\xa6I\x02\b\x01R\x13configurationStatus\x12i\n" +
	"\x1econfiguration_status_indicator\x18\x0e \x01(\x0e2\x1b.status.v1.StatusIndicationB\x06\xba\xa6I\x02\b\x01R\x1cconfigurationStatusIndicator\x12L\n" +
	"\x1econfiguration_status_timestamp\x18\x0f \x01(\x04B\x06\xba\xa6I\x02\b\x01R\x1cconfigurationStatusTimestamp\x122\n" +
	"\ttenant_id\x18d \x01(\tB\x15\xbaH\n" +
	"\xd8\x01\x01r\x05($\xb0\x01\x01\xba\xa6I\x04\b\x00(\x01R\btenantId\x12?\n" +
	"\n" +
	"created_at\x18\xc8\x01 \x01(\tB\x1f\xba\xa6I\x1b\b\x00(\x01J\x15\n" +
	"\bpostgres\x12\tTIMESTAMPR\tcreatedAt\x12?\n" +
	"\n" +
	"updated_at\x18\xc9\x01 \x01(\tB\x1f\xba\xa6I\x1b\b\x00(\x00J\x15\n" +
	"\bpostgres\x12\tTIMESTAMPR\tupdatedAt:\x19\xb2\xf9\x03\x0f\n" +
	"\r\x12\ttenant_id\x18\x00\xba\xa6I\x02\b\x01*\xdf\x01\n" +
	"\x11RemoteAccessState\x12#\n" +
	"\x1fREMOTE_ACCESS_STATE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bREMOTE_ACCESS_STATE_DELETED\x10\x01\x12\x1d\n" +
	"\x19REMOTE_ACCESS_STATE_ERROR\x10\x02\x12\x1f\n" +
	"\x1bREMOTE_ACCESS_STATE_ENABLED\x10\x03\x12 \n" +
	"\x1cREMOTE_ACCESS_STATE_DISABLED\x10\x04\x12\"\n" +
	"\x1eREMOTE_ACCESS_STATE_CONFIGURED\x10\x05BOZMgithub.com/open-edge-platform/infra-core/inventory/v2/pkg/api/remoteaccess/v1b\x06proto3"

var (
	file_remoteaccess_v1_remoteaccess_proto_rawDescOnce sync.Once
	file_remoteaccess_v1_remoteaccess_proto_rawDescData []byte
)

func file_remoteaccess_v1_remoteaccess_proto_rawDescGZIP() []byte {
	file_remoteaccess_v1_remoteaccess_proto_rawDescOnce.Do(func() {
		file_remoteaccess_v1_remoteaccess_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remoteaccess_v1_remoteaccess_proto_rawDesc), len(file_remoteaccess_v1_remoteaccess_proto_rawDesc)))
	})
	return file_remoteaccess_v1_remoteaccess_proto_rawDescData
}

var file_remoteaccess_v1_remoteaccess_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_remoteaccess_v1_remoteaccess_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_remoteaccess_v1_remoteaccess_proto_goTypes = []any{
	(RemoteAccessState)(0),            // 0: remoteaccess.v1.RemoteAccessState
	(*RemoteAccessConfiguration)(nil), // 1: remoteaccess.v1.RemoteAccessConfiguration
	(*v1.InstanceResource)(nil),       // 2: compute.v1.InstanceResource
	(v11.StatusIndication)(0),         // 3: status.v1.StatusIndication
}
var file_remoteaccess_v1_remoteaccess_proto_depIdxs = []int32{
	2, // 0: remoteaccess.v1.RemoteAccessConfiguration.instance:type_name -> compute.v1.InstanceResource
	0, // 1: remoteaccess.v1.RemoteAccessConfiguration.current_state:type_name -> remoteaccess.v1.RemoteAccessState
	0, // 2: remoteaccess.v1.RemoteAccessConfiguration.desired_state:type_name -> remoteaccess.v1.RemoteAccessState
	3, // 3: remoteaccess.v1.RemoteAccessConfiguration.configuration_status_indicator:type_name -> status.v1.StatusIndication
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_remoteaccess_v1_remoteaccess_proto_init() }
func file_remoteaccess_v1_remoteaccess_proto_init() {
	if File_remoteaccess_v1_remoteaccess_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_remoteaccess_v1_remoteaccess_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteAccessConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remoteaccess_v1_remoteaccess_proto_rawDesc), len(file_remoteaccess_v1_remoteaccess_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_remoteaccess_v1_remoteaccess_proto_goTypes,
		DependencyIndexes: file_remoteaccess_v1_remoteaccess_proto_depIdxs,
		EnumInfos:         file_remoteaccess_v1_remoteaccess_proto_enumTypes,
		MessageInfos:      file_remoteaccess_v1_remoteaccess_proto_msgTypes,
	}.Build()
	File_remoteaccess_v1_remoteaccess_proto = out.File
	file_remoteaccess_v1_remoteaccess_proto_goTypes = nil
	file_remoteaccess_v1_remoteaccess_proto_depIdxs = nil
}
