// Code generated by ent, DO NOT EDIT.

package remoteaccessconfiguration

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/open-edge-platform/infra-core/inventory/v2/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLTE(FieldID, id))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldResourceID, v))
}

// ExpirationTimestamp applies equality check predicate on the "expiration_timestamp" field. It's identical to ExpirationTimestampEQ.
func ExpirationTimestamp(v uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldExpirationTimestamp, v))
}

// LocalPort applies equality check predicate on the "local_port" field. It's identical to LocalPortEQ.
func LocalPort(v uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldLocalPort, v))
}

// ProxyHost applies equality check predicate on the "proxy_host" field. It's identical to ProxyHostEQ.
func ProxyHost(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldProxyHost, v))
}

// User applies equality check predicate on the "user" field. It's identical to UserEQ.
func User(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldUser, v))
}

// SessionToken applies equality check predicate on the "session_token" field. It's identical to SessionTokenEQ.
func SessionToken(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldSessionToken, v))
}

// TargetHost applies equality check predicate on the "target_host" field. It's identical to TargetHostEQ.
func TargetHost(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldTargetHost, v))
}

// TargetPort applies equality check predicate on the "target_port" field. It's identical to TargetPortEQ.
func TargetPort(v uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldTargetPort, v))
}

// ConfigurationStatus applies equality check predicate on the "configuration_status" field. It's identical to ConfigurationStatusEQ.
func ConfigurationStatus(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldConfigurationStatus, v))
}

// ConfigurationStatusTimestamp applies equality check predicate on the "configuration_status_timestamp" field. It's identical to ConfigurationStatusTimestampEQ.
func ConfigurationStatusTimestamp(v uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldConfigurationStatusTimestamp, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldTenantID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldUpdatedAt, v))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotIn(FieldResourceID, vs...))
}

// ResourceIDGT applies the GT predicate on the "resource_id" field.
func ResourceIDGT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGT(FieldResourceID, v))
}

// ResourceIDGTE applies the GTE predicate on the "resource_id" field.
func ResourceIDGTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGTE(FieldResourceID, v))
}

// ResourceIDLT applies the LT predicate on the "resource_id" field.
func ResourceIDLT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLT(FieldResourceID, v))
}

// ResourceIDLTE applies the LTE predicate on the "resource_id" field.
func ResourceIDLTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLTE(FieldResourceID, v))
}

// ResourceIDContains applies the Contains predicate on the "resource_id" field.
func ResourceIDContains(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContains(FieldResourceID, v))
}

// ResourceIDHasPrefix applies the HasPrefix predicate on the "resource_id" field.
func ResourceIDHasPrefix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasPrefix(FieldResourceID, v))
}

// ResourceIDHasSuffix applies the HasSuffix predicate on the "resource_id" field.
func ResourceIDHasSuffix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasSuffix(FieldResourceID, v))
}

// ResourceIDEqualFold applies the EqualFold predicate on the "resource_id" field.
func ResourceIDEqualFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEqualFold(FieldResourceID, v))
}

// ResourceIDContainsFold applies the ContainsFold predicate on the "resource_id" field.
func ResourceIDContainsFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContainsFold(FieldResourceID, v))
}

// ExpirationTimestampEQ applies the EQ predicate on the "expiration_timestamp" field.
func ExpirationTimestampEQ(v uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldExpirationTimestamp, v))
}

// ExpirationTimestampNEQ applies the NEQ predicate on the "expiration_timestamp" field.
func ExpirationTimestampNEQ(v uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNEQ(FieldExpirationTimestamp, v))
}

// ExpirationTimestampIn applies the In predicate on the "expiration_timestamp" field.
func ExpirationTimestampIn(vs ...uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIn(FieldExpirationTimestamp, vs...))
}

// ExpirationTimestampNotIn applies the NotIn predicate on the "expiration_timestamp" field.
func ExpirationTimestampNotIn(vs ...uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotIn(FieldExpirationTimestamp, vs...))
}

// ExpirationTimestampGT applies the GT predicate on the "expiration_timestamp" field.
func ExpirationTimestampGT(v uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGT(FieldExpirationTimestamp, v))
}

// ExpirationTimestampGTE applies the GTE predicate on the "expiration_timestamp" field.
func ExpirationTimestampGTE(v uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGTE(FieldExpirationTimestamp, v))
}

// ExpirationTimestampLT applies the LT predicate on the "expiration_timestamp" field.
func ExpirationTimestampLT(v uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLT(FieldExpirationTimestamp, v))
}

// ExpirationTimestampLTE applies the LTE predicate on the "expiration_timestamp" field.
func ExpirationTimestampLTE(v uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLTE(FieldExpirationTimestamp, v))
}

// LocalPortEQ applies the EQ predicate on the "local_port" field.
func LocalPortEQ(v uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldLocalPort, v))
}

// LocalPortNEQ applies the NEQ predicate on the "local_port" field.
func LocalPortNEQ(v uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNEQ(FieldLocalPort, v))
}

// LocalPortIn applies the In predicate on the "local_port" field.
func LocalPortIn(vs ...uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIn(FieldLocalPort, vs...))
}

// LocalPortNotIn applies the NotIn predicate on the "local_port" field.
func LocalPortNotIn(vs ...uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotIn(FieldLocalPort, vs...))
}

// LocalPortGT applies the GT predicate on the "local_port" field.
func LocalPortGT(v uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGT(FieldLocalPort, v))
}

// LocalPortGTE applies the GTE predicate on the "local_port" field.
func LocalPortGTE(v uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGTE(FieldLocalPort, v))
}

// LocalPortLT applies the LT predicate on the "local_port" field.
func LocalPortLT(v uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLT(FieldLocalPort, v))
}

// LocalPortLTE applies the LTE predicate on the "local_port" field.
func LocalPortLTE(v uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLTE(FieldLocalPort, v))
}

// LocalPortIsNil applies the IsNil predicate on the "local_port" field.
func LocalPortIsNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIsNull(FieldLocalPort))
}

// LocalPortNotNil applies the NotNil predicate on the "local_port" field.
func LocalPortNotNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotNull(FieldLocalPort))
}

// ProxyHostEQ applies the EQ predicate on the "proxy_host" field.
func ProxyHostEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldProxyHost, v))
}

// ProxyHostNEQ applies the NEQ predicate on the "proxy_host" field.
func ProxyHostNEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNEQ(FieldProxyHost, v))
}

// ProxyHostIn applies the In predicate on the "proxy_host" field.
func ProxyHostIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIn(FieldProxyHost, vs...))
}

// ProxyHostNotIn applies the NotIn predicate on the "proxy_host" field.
func ProxyHostNotIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotIn(FieldProxyHost, vs...))
}

// ProxyHostGT applies the GT predicate on the "proxy_host" field.
func ProxyHostGT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGT(FieldProxyHost, v))
}

// ProxyHostGTE applies the GTE predicate on the "proxy_host" field.
func ProxyHostGTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGTE(FieldProxyHost, v))
}

// ProxyHostLT applies the LT predicate on the "proxy_host" field.
func ProxyHostLT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLT(FieldProxyHost, v))
}

// ProxyHostLTE applies the LTE predicate on the "proxy_host" field.
func ProxyHostLTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLTE(FieldProxyHost, v))
}

// ProxyHostContains applies the Contains predicate on the "proxy_host" field.
func ProxyHostContains(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContains(FieldProxyHost, v))
}

// ProxyHostHasPrefix applies the HasPrefix predicate on the "proxy_host" field.
func ProxyHostHasPrefix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasPrefix(FieldProxyHost, v))
}

// ProxyHostHasSuffix applies the HasSuffix predicate on the "proxy_host" field.
func ProxyHostHasSuffix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasSuffix(FieldProxyHost, v))
}

// ProxyHostIsNil applies the IsNil predicate on the "proxy_host" field.
func ProxyHostIsNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIsNull(FieldProxyHost))
}

// ProxyHostNotNil applies the NotNil predicate on the "proxy_host" field.
func ProxyHostNotNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotNull(FieldProxyHost))
}

// ProxyHostEqualFold applies the EqualFold predicate on the "proxy_host" field.
func ProxyHostEqualFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEqualFold(FieldProxyHost, v))
}

// ProxyHostContainsFold applies the ContainsFold predicate on the "proxy_host" field.
func ProxyHostContainsFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContainsFold(FieldProxyHost, v))
}

// UserEQ applies the EQ predicate on the "user" field.
func UserEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldUser, v))
}

// UserNEQ applies the NEQ predicate on the "user" field.
func UserNEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNEQ(FieldUser, v))
}

// UserIn applies the In predicate on the "user" field.
func UserIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIn(FieldUser, vs...))
}

// UserNotIn applies the NotIn predicate on the "user" field.
func UserNotIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotIn(FieldUser, vs...))
}

// UserGT applies the GT predicate on the "user" field.
func UserGT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGT(FieldUser, v))
}

// UserGTE applies the GTE predicate on the "user" field.
func UserGTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGTE(FieldUser, v))
}

// UserLT applies the LT predicate on the "user" field.
func UserLT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLT(FieldUser, v))
}

// UserLTE applies the LTE predicate on the "user" field.
func UserLTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLTE(FieldUser, v))
}

// UserContains applies the Contains predicate on the "user" field.
func UserContains(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContains(FieldUser, v))
}

// UserHasPrefix applies the HasPrefix predicate on the "user" field.
func UserHasPrefix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasPrefix(FieldUser, v))
}

// UserHasSuffix applies the HasSuffix predicate on the "user" field.
func UserHasSuffix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasSuffix(FieldUser, v))
}

// UserIsNil applies the IsNil predicate on the "user" field.
func UserIsNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIsNull(FieldUser))
}

// UserNotNil applies the NotNil predicate on the "user" field.
func UserNotNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotNull(FieldUser))
}

// UserEqualFold applies the EqualFold predicate on the "user" field.
func UserEqualFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEqualFold(FieldUser, v))
}

// UserContainsFold applies the ContainsFold predicate on the "user" field.
func UserContainsFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContainsFold(FieldUser, v))
}

// SessionTokenEQ applies the EQ predicate on the "session_token" field.
func SessionTokenEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldSessionToken, v))
}

// SessionTokenNEQ applies the NEQ predicate on the "session_token" field.
func SessionTokenNEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNEQ(FieldSessionToken, v))
}

// SessionTokenIn applies the In predicate on the "session_token" field.
func SessionTokenIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIn(FieldSessionToken, vs...))
}

// SessionTokenNotIn applies the NotIn predicate on the "session_token" field.
func SessionTokenNotIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotIn(FieldSessionToken, vs...))
}

// SessionTokenGT applies the GT predicate on the "session_token" field.
func SessionTokenGT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGT(FieldSessionToken, v))
}

// SessionTokenGTE applies the GTE predicate on the "session_token" field.
func SessionTokenGTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGTE(FieldSessionToken, v))
}

// SessionTokenLT applies the LT predicate on the "session_token" field.
func SessionTokenLT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLT(FieldSessionToken, v))
}

// SessionTokenLTE applies the LTE predicate on the "session_token" field.
func SessionTokenLTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLTE(FieldSessionToken, v))
}

// SessionTokenContains applies the Contains predicate on the "session_token" field.
func SessionTokenContains(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContains(FieldSessionToken, v))
}

// SessionTokenHasPrefix applies the HasPrefix predicate on the "session_token" field.
func SessionTokenHasPrefix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasPrefix(FieldSessionToken, v))
}

// SessionTokenHasSuffix applies the HasSuffix predicate on the "session_token" field.
func SessionTokenHasSuffix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasSuffix(FieldSessionToken, v))
}

// SessionTokenIsNil applies the IsNil predicate on the "session_token" field.
func SessionTokenIsNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIsNull(FieldSessionToken))
}

// SessionTokenNotNil applies the NotNil predicate on the "session_token" field.
func SessionTokenNotNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotNull(FieldSessionToken))
}

// SessionTokenEqualFold applies the EqualFold predicate on the "session_token" field.
func SessionTokenEqualFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEqualFold(FieldSessionToken, v))
}

// SessionTokenContainsFold applies the ContainsFold predicate on the "session_token" field.
func SessionTokenContainsFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContainsFold(FieldSessionToken, v))
}

// TargetHostEQ applies the EQ predicate on the "target_host" field.
func TargetHostEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldTargetHost, v))
}

// TargetHostNEQ applies the NEQ predicate on the "target_host" field.
func TargetHostNEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNEQ(FieldTargetHost, v))
}

// TargetHostIn applies the In predicate on the "target_host" field.
func TargetHostIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIn(FieldTargetHost, vs...))
}

// TargetHostNotIn applies the NotIn predicate on the "target_host" field.
func TargetHostNotIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotIn(FieldTargetHost, vs...))
}

// TargetHostGT applies the GT predicate on the "target_host" field.
func TargetHostGT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGT(FieldTargetHost, v))
}

// TargetHostGTE applies the GTE predicate on the "target_host" field.
func TargetHostGTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGTE(FieldTargetHost, v))
}

// TargetHostLT applies the LT predicate on the "target_host" field.
func TargetHostLT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLT(FieldTargetHost, v))
}

// TargetHostLTE applies the LTE predicate on the "target_host" field.
func TargetHostLTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLTE(FieldTargetHost, v))
}

// TargetHostContains applies the Contains predicate on the "target_host" field.
func TargetHostContains(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContains(FieldTargetHost, v))
}

// TargetHostHasPrefix applies the HasPrefix predicate on the "target_host" field.
func TargetHostHasPrefix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasPrefix(FieldTargetHost, v))
}

// TargetHostHasSuffix applies the HasSuffix predicate on the "target_host" field.
func TargetHostHasSuffix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasSuffix(FieldTargetHost, v))
}

// TargetHostIsNil applies the IsNil predicate on the "target_host" field.
func TargetHostIsNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIsNull(FieldTargetHost))
}

// TargetHostNotNil applies the NotNil predicate on the "target_host" field.
func TargetHostNotNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotNull(FieldTargetHost))
}

// TargetHostEqualFold applies the EqualFold predicate on the "target_host" field.
func TargetHostEqualFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEqualFold(FieldTargetHost, v))
}

// TargetHostContainsFold applies the ContainsFold predicate on the "target_host" field.
func TargetHostContainsFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContainsFold(FieldTargetHost, v))
}

// TargetPortEQ applies the EQ predicate on the "target_port" field.
func TargetPortEQ(v uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldTargetPort, v))
}

// TargetPortNEQ applies the NEQ predicate on the "target_port" field.
func TargetPortNEQ(v uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNEQ(FieldTargetPort, v))
}

// TargetPortIn applies the In predicate on the "target_port" field.
func TargetPortIn(vs ...uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIn(FieldTargetPort, vs...))
}

// TargetPortNotIn applies the NotIn predicate on the "target_port" field.
func TargetPortNotIn(vs ...uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotIn(FieldTargetPort, vs...))
}

// TargetPortGT applies the GT predicate on the "target_port" field.
func TargetPortGT(v uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGT(FieldTargetPort, v))
}

// TargetPortGTE applies the GTE predicate on the "target_port" field.
func TargetPortGTE(v uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGTE(FieldTargetPort, v))
}

// TargetPortLT applies the LT predicate on the "target_port" field.
func TargetPortLT(v uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLT(FieldTargetPort, v))
}

// TargetPortLTE applies the LTE predicate on the "target_port" field.
func TargetPortLTE(v uint32) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLTE(FieldTargetPort, v))
}

// TargetPortIsNil applies the IsNil predicate on the "target_port" field.
func TargetPortIsNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIsNull(FieldTargetPort))
}

// TargetPortNotNil applies the NotNil predicate on the "target_port" field.
func TargetPortNotNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotNull(FieldTargetPort))
}

// CurrentStateEQ applies the EQ predicate on the "current_state" field.
func CurrentStateEQ(v CurrentState) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldCurrentState, v))
}

// CurrentStateNEQ applies the NEQ predicate on the "current_state" field.
func CurrentStateNEQ(v CurrentState) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNEQ(FieldCurrentState, v))
}

// CurrentStateIn applies the In predicate on the "current_state" field.
func CurrentStateIn(vs ...CurrentState) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIn(FieldCurrentState, vs...))
}

// CurrentStateNotIn applies the NotIn predicate on the "current_state" field.
func CurrentStateNotIn(vs ...CurrentState) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotIn(FieldCurrentState, vs...))
}

// CurrentStateIsNil applies the IsNil predicate on the "current_state" field.
func CurrentStateIsNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIsNull(FieldCurrentState))
}

// CurrentStateNotNil applies the NotNil predicate on the "current_state" field.
func CurrentStateNotNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotNull(FieldCurrentState))
}

// DesiredStateEQ applies the EQ predicate on the "desired_state" field.
func DesiredStateEQ(v DesiredState) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldDesiredState, v))
}

// DesiredStateNEQ applies the NEQ predicate on the "desired_state" field.
func DesiredStateNEQ(v DesiredState) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNEQ(FieldDesiredState, v))
}

// DesiredStateIn applies the In predicate on the "desired_state" field.
func DesiredStateIn(vs ...DesiredState) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIn(FieldDesiredState, vs...))
}

// DesiredStateNotIn applies the NotIn predicate on the "desired_state" field.
func DesiredStateNotIn(vs ...DesiredState) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotIn(FieldDesiredState, vs...))
}

// ConfigurationStatusEQ applies the EQ predicate on the "configuration_status" field.
func ConfigurationStatusEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldConfigurationStatus, v))
}

// ConfigurationStatusNEQ applies the NEQ predicate on the "configuration_status" field.
func ConfigurationStatusNEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNEQ(FieldConfigurationStatus, v))
}

// ConfigurationStatusIn applies the In predicate on the "configuration_status" field.
func ConfigurationStatusIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIn(FieldConfigurationStatus, vs...))
}

// ConfigurationStatusNotIn applies the NotIn predicate on the "configuration_status" field.
func ConfigurationStatusNotIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotIn(FieldConfigurationStatus, vs...))
}

// ConfigurationStatusGT applies the GT predicate on the "configuration_status" field.
func ConfigurationStatusGT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGT(FieldConfigurationStatus, v))
}

// ConfigurationStatusGTE applies the GTE predicate on the "configuration_status" field.
func ConfigurationStatusGTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGTE(FieldConfigurationStatus, v))
}

// ConfigurationStatusLT applies the LT predicate on the "configuration_status" field.
func ConfigurationStatusLT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLT(FieldConfigurationStatus, v))
}

// ConfigurationStatusLTE applies the LTE predicate on the "configuration_status" field.
func ConfigurationStatusLTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLTE(FieldConfigurationStatus, v))
}

// ConfigurationStatusContains applies the Contains predicate on the "configuration_status" field.
func ConfigurationStatusContains(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContains(FieldConfigurationStatus, v))
}

// ConfigurationStatusHasPrefix applies the HasPrefix predicate on the "configuration_status" field.
func ConfigurationStatusHasPrefix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasPrefix(FieldConfigurationStatus, v))
}

// ConfigurationStatusHasSuffix applies the HasSuffix predicate on the "configuration_status" field.
func ConfigurationStatusHasSuffix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasSuffix(FieldConfigurationStatus, v))
}

// ConfigurationStatusIsNil applies the IsNil predicate on the "configuration_status" field.
func ConfigurationStatusIsNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIsNull(FieldConfigurationStatus))
}

// ConfigurationStatusNotNil applies the NotNil predicate on the "configuration_status" field.
func ConfigurationStatusNotNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotNull(FieldConfigurationStatus))
}

// ConfigurationStatusEqualFold applies the EqualFold predicate on the "configuration_status" field.
func ConfigurationStatusEqualFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEqualFold(FieldConfigurationStatus, v))
}

// ConfigurationStatusContainsFold applies the ContainsFold predicate on the "configuration_status" field.
func ConfigurationStatusContainsFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContainsFold(FieldConfigurationStatus, v))
}

// ConfigurationStatusIndicatorEQ applies the EQ predicate on the "configuration_status_indicator" field.
func ConfigurationStatusIndicatorEQ(v ConfigurationStatusIndicator) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldConfigurationStatusIndicator, v))
}

// ConfigurationStatusIndicatorNEQ applies the NEQ predicate on the "configuration_status_indicator" field.
func ConfigurationStatusIndicatorNEQ(v ConfigurationStatusIndicator) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNEQ(FieldConfigurationStatusIndicator, v))
}

// ConfigurationStatusIndicatorIn applies the In predicate on the "configuration_status_indicator" field.
func ConfigurationStatusIndicatorIn(vs ...ConfigurationStatusIndicator) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIn(FieldConfigurationStatusIndicator, vs...))
}

// ConfigurationStatusIndicatorNotIn applies the NotIn predicate on the "configuration_status_indicator" field.
func ConfigurationStatusIndicatorNotIn(vs ...ConfigurationStatusIndicator) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotIn(FieldConfigurationStatusIndicator, vs...))
}

// ConfigurationStatusIndicatorIsNil applies the IsNil predicate on the "configuration_status_indicator" field.
func ConfigurationStatusIndicatorIsNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIsNull(FieldConfigurationStatusIndicator))
}

// ConfigurationStatusIndicatorNotNil applies the NotNil predicate on the "configuration_status_indicator" field.
func ConfigurationStatusIndicatorNotNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotNull(FieldConfigurationStatusIndicator))
}

// ConfigurationStatusTimestampEQ applies the EQ predicate on the "configuration_status_timestamp" field.
func ConfigurationStatusTimestampEQ(v uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldConfigurationStatusTimestamp, v))
}

// ConfigurationStatusTimestampNEQ applies the NEQ predicate on the "configuration_status_timestamp" field.
func ConfigurationStatusTimestampNEQ(v uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNEQ(FieldConfigurationStatusTimestamp, v))
}

// ConfigurationStatusTimestampIn applies the In predicate on the "configuration_status_timestamp" field.
func ConfigurationStatusTimestampIn(vs ...uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIn(FieldConfigurationStatusTimestamp, vs...))
}

// ConfigurationStatusTimestampNotIn applies the NotIn predicate on the "configuration_status_timestamp" field.
func ConfigurationStatusTimestampNotIn(vs ...uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotIn(FieldConfigurationStatusTimestamp, vs...))
}

// ConfigurationStatusTimestampGT applies the GT predicate on the "configuration_status_timestamp" field.
func ConfigurationStatusTimestampGT(v uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGT(FieldConfigurationStatusTimestamp, v))
}

// ConfigurationStatusTimestampGTE applies the GTE predicate on the "configuration_status_timestamp" field.
func ConfigurationStatusTimestampGTE(v uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGTE(FieldConfigurationStatusTimestamp, v))
}

// ConfigurationStatusTimestampLT applies the LT predicate on the "configuration_status_timestamp" field.
func ConfigurationStatusTimestampLT(v uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLT(FieldConfigurationStatusTimestamp, v))
}

// ConfigurationStatusTimestampLTE applies the LTE predicate on the "configuration_status_timestamp" field.
func ConfigurationStatusTimestampLTE(v uint64) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLTE(FieldConfigurationStatusTimestamp, v))
}

// ConfigurationStatusTimestampIsNil applies the IsNil predicate on the "configuration_status_timestamp" field.
func ConfigurationStatusTimestampIsNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIsNull(FieldConfigurationStatusTimestamp))
}

// ConfigurationStatusTimestampNotNil applies the NotNil predicate on the "configuration_status_timestamp" field.
func ConfigurationStatusTimestampNotNil() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotNull(FieldConfigurationStatusTimestamp))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContainsFold(FieldTenantID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtContains applies the Contains predicate on the "created_at" field.
func CreatedAtContains(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContains(FieldCreatedAt, v))
}

// CreatedAtHasPrefix applies the HasPrefix predicate on the "created_at" field.
func CreatedAtHasPrefix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasPrefix(FieldCreatedAt, v))
}

// CreatedAtHasSuffix applies the HasSuffix predicate on the "created_at" field.
func CreatedAtHasSuffix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasSuffix(FieldCreatedAt, v))
}

// CreatedAtEqualFold applies the EqualFold predicate on the "created_at" field.
func CreatedAtEqualFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEqualFold(FieldCreatedAt, v))
}

// CreatedAtContainsFold applies the ContainsFold predicate on the "created_at" field.
func CreatedAtContainsFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContainsFold(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtContains applies the Contains predicate on the "updated_at" field.
func UpdatedAtContains(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContains(FieldUpdatedAt, v))
}

// UpdatedAtHasPrefix applies the HasPrefix predicate on the "updated_at" field.
func UpdatedAtHasPrefix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasPrefix(FieldUpdatedAt, v))
}

// UpdatedAtHasSuffix applies the HasSuffix predicate on the "updated_at" field.
func UpdatedAtHasSuffix(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldHasSuffix(FieldUpdatedAt, v))
}

// UpdatedAtEqualFold applies the EqualFold predicate on the "updated_at" field.
func UpdatedAtEqualFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldEqualFold(FieldUpdatedAt, v))
}

// UpdatedAtContainsFold applies the ContainsFold predicate on the "updated_at" field.
func UpdatedAtContainsFold(v string) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.FieldContainsFold(FieldUpdatedAt, v))
}

// HasInstance applies the HasEdge predicate on the "instance" edge.
func HasInstance() predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, InstanceTable, InstanceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInstanceWith applies the HasEdge predicate on the "instance" edge with a given conditions (other predicates).
func HasInstanceWith(preds ...predicate.InstanceResource) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(func(s *sql.Selector) {
		step := newInstanceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RemoteAccessConfiguration) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RemoteAccessConfiguration) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RemoteAccessConfiguration) predicate.RemoteAccessConfiguration {
	return predicate.RemoteAccessConfiguration(sql.NotPredicates(p))
}
